{% set name = "limix-core" %}
{% set version = "1.0.2" %}
{% set sha256 = "8d0799073060c9d108adf427f4d450cc34daf40fd9384723ac083aad1a929670" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy >=1.10
    - scipy >=0.18
    - six

test:
  requires:
    - pytest >=3
  imports:
    - limix_core
  commands:
    - python -c "import sys; import limix_core; sys.exit(limix_core.test())"

about:
  home: https://github.com/limix/limix-core
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Fast inference for Linear Mixed Models'
  dev_url: https://github.com/limix/limix-core

extra:
  recipe-maintainers:
    - Horta
