travis:
  secure:
    BINSTAR_TOKEN: iiN0lBAaDduwvwZp6GdxAqqSZLSttsk/DjJmR6xMTGLT9BGd67zhk3XBfqwjZOTbe9embnmr4XfST4HxIQ2rsSTMaTZcB3jiJCpypKGgKEkN4T4hZR7kuGlI+DBU9dQ91MTaizpqcc1F1CNOodSBwOa61HhKbbkdVrveb4Qh0N4PwdqlBnjnS+w7n10Ctbzfevcq/omp29chAa56qpsRSbdSddpMkqYRm2ZjGiB3hniYmkWifSVZiZCcrvLvBnv5Q9hsOh1v7zZmnj+4uyXYe8lN1gxM2kqO0DfJQswexVLDlFrErORlerF4bz5fi5NZzTy1Xgf9r10Zv8vcOwytOwkzmETt9wvjLSlA+4Uarr1+4J3JznENn9p4NPCaqJKtni/7Ll5eUnpM6zjBkdjmE8H7Uiw5to3MgDUjOHN1byjLr4jFWq80srxkbEe3fimM5X9zYfMy2Wp93NSyDyVyqgkoVlzcC10+259e4RO+hRksHxMyujzkz6DKlugNL7/rj6HiMYiKTdom70lucI7QmMG+2+qsEH+T1zcZC9hDR0fusjZPMP8YNcwpJDPujwEbVD/wqIBa2/SCPJ6CUJtzCjWAW/JSqOXNhFJBdM8nmlYYpiDPs/b4BszI1JVb18GS6HOZlcHNAL8XQhTT2DyxXFNsRuPFndMt40ok8/sMrek=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
