travis:
  secure:
    BINSTAR_TOKEN: GhDX/Hz6Abcd2UezmQK9tsJCHdERqSSbHSBjPUEWtlitebawT/wifiXbIR1eax5FcPuF18+seLhzTxDYgmlpY3ciKlWcQn7QCCY+iT4oiXe2X4yutH/Rz6AfzmpAbAlGQVvvBjPUHohQ/Cs8DabOX2Tq0RqHitORZKAXsLQllJIDO3BJhS9NrnkXjDXUPbUHlHlKmgEJMDRlUbuMJLh71zwPq4Md+FiliGK8dmK0oyNiG6cAdHu2eCrNJ8Y9Xkh0Ud6TsVZFfXJJrEj9R5vWQRdNyPEdIWdQZCZXFsebpMZZomy+AWB3XX9M0dQtC+THJBUnkerOZTWQVLP/YgU1BO6/WGd1tgGdOTNLkoieF6y3JwUG6JcJ8JYXANTdTK/kQLYnR+RwKHwGeU4L2ivqQjx5ohX0o9i9syaSOtvBIRT0L45oKefGEn4Je/VEpR5ZIuGd3qbwpdil+00iECpv8Ixh7kzzVcVgyd8TWuenOOn4+FAraG5nY+uTz3VOIabtbNlCHt+q/7WRjxrIfa3ykvXqNwdiyUVWMeTkT+DM8A1eqgoJfXZwBygn0HlmB8iLns0pmYFVCeIqVlqb9TLD0+4l9d2TrmuM1BJS1D4nv6MyXrc5bfJfwm1YOTPlIidBslXq/JtPMM1NODcpgZkMgedYIzHb30fTXoxBp12m9SM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
